### ISSUE TITLE
Update to Howto wikis

### ISSUE THREAD

**Issue by wile1411** [MOARdV/FlightSystemsRedux#1]
Noticed the 'How to DSKY' wiki in this FlightSystemsRedux repo was different to the MOARdVPlus repo wiki which has an updated screenshot / descriptions.
https://github.com/MOARdV/MOARdVPlus/wiki/How-to-DSKY
vs
https://github.com/MOARdV/FlightSystemsRedux/wiki/How-to-DSKY

For others, the the reverse is true in that the FlightSystemsRedux repo has better documentation than MOARdVPlus. eg X-pointer.

**Comment by MOARdV** [comment]
FlightSystemsRedux is a RasterPropMonitor mod, and I'm no longer developing it, so I won't be refreshing the info here.  I will update the MOARdVPlus how-to wiki when I have time to create MAS-accurate images of the props while in use.
